# Backend Deployment Workflow
# أتمتة نشر Backend (Laravel PHP)

name: Backend Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to backend server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
          
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
            cd /var/www/laravel-app
            git pull origin main
            composer install --no-dev
            php artisan migrate --force
            php artisan cache:clear
            echo "Backend deployment successful"
          EOF
